config/routes.rb
Rails.application.routes.draw do
  get 'usersessions/new'
  get 'usersessions/create'
  get 'usersessions/destroy'
  get 'favorites/update'
  get 'users/list'
  get 'movies/userlist'
  get 'movies/userlist/:user_id', to: 'movies#userfav'
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources 'movies'
  resources 'users'
  root 'usersessions#new'
  get 'admin', to: 'movies#index'
  resources 'favorites'
  # get 'logout', to: 'usersessions#destroy', as: 'logout'
  resources 'usersessions'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true,  length: { maximum: 80 }
  validates :geners, presence: true
    validates :year, presence: true, length:{ minimum: 4, maximum: 4 }
    validates :director, length: { maximum: 60 }
    validates :main_star, length: { maximum: 60 }
    validates :description, length: { maximum: 400}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, :dependent => :delete_all
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def favorite_text
    return @favorite_exists ? 'UnFavorite' : 'Favorite'
  end
  helper_method :favorite_text
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    favorite = Favorite.where(movie: Movie.find(params[:movie]), user: current_user) 
    if favorite.empty?
      favorite = Favorite.create(movie: Movie.find(params[:movie]), user: current_user)
      # @favorite_exists = true
      render json: {status: 'SUCESS', message: 'movie is favorited', data: favorite}
    else
      favorite.destroy_all
      # @favorite_exists = false
      render json: {status: 'SUCESS', message:'movie is unfavorited', data: favorite}
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @movies = Movie.all
  end

  def show
   @movies = Movie.find(params[:id])
  end

  def create
    @movies = Movie.new(movies_params)
    if @movies.save
      redirect_to @movies
    else
      render 'new'
    end
  end

  def destroy
    @movies = Movie.find(params[:id])
    @movies.destroy
    redirect_to @movies
  end

  def edit
    @movies = Movie.find(params[:id])
  end

  def update
    @movies = Movie.find(params[:id])
    if @movies.update(movies_params)
      redirect_to @movies
    else
      render 'edit'
    end   
  end

  def userlist
    @users = User.all
  end

  def userfav
    @favorites = User.find(params[:user_id]).favorites
  end

  private

  def movies_params
    params.require(:movie).permit(:name, :geners, :year, :director, :main_star, :description, :Favorited)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @movies = Movie.all
    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end

  def show
    @favorite_exists = Favorite.where(movie: @movies,user: current_user) == [] ? false : true
    @movies = Movie.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end
  def list
    @favorites = current_user.favorites
    respond_to do |format|
      format.html
      format.json { render json: @favorites }
    end
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy
  end
end

app/controllers/usersessions_controller.rb
class UsersessionsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    user = User.find_by_username(params[:username])
    if user 
      session[:user_id] = user.id
      redirect_to users_list_path, notice: "Logged in!"
    else
      user = User.new(username: params[:username])
      user.save
      session[:user_id] = user.id
      redirect_to users_path, notice: "Logged in!"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to sessions_new_path, notice: "Logged out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usersessions_helper.rb
module UsersessionsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/favorites/update.html.erb
$('#favorite_link').tetxt("<%= favorite_text %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>edit movies</h1>


<%= form_with(model: @movies, local: true) do |f| %>
	<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %> 
	</p>

	<p>
    <%= f.label :genres %> <br>
     <%= f.select :geners, options_for_select([["Select genres"], "Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "History", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"], selected: f.object.geners) %>
	</p>

  <p>
    <%= f.label :year %> <br>
    <%= f.number_field :year %> 
	</p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %> 
	</p>

  <p>
    <%= f.label :director %> <br>
    <%= f.text_area :director %> 
	</p>

  <p>
    <%= f.label :main_star %> <br>
    <%= f.text_area :main_star %> 
	</p>


  <p>
    <%= f.submit %>
  </p>


<% end %>
<%= link_to 'Back',movies_path%>

app/views/movies/index.html.erb
<h1>Movies listing page</h1>
<%= link_to 'Add movies',new_movie_path%> || <%= link_to 'Users list',movies_userlist_path%>
<table border="2">
  <thead>
    <tr>
      <th>name</th>
      <th>year</th>
      <th>Favorited</th>
      <th col='3'>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %> 
      <tr>
        <td><%= link_to movie.name, edit_movie_path(movie.id)  %></td>
        <td><%= movie.year %></td>
        <td><%=Favorite.where(movie_id: movie.id).count%></td>
        <td><%= link_to 'show', movie_path(movie.id)%></td>
        <td><%= link_to 'delete', movie_path(movie.id), method: :delete, data: {confirm: "Are You Sure?"} %></td>
      </tr>
    <% end %>
  
  </tbody>
</table>

<%= link_to('Logout', destroy_admin_session_path, method: :delete) %>

app/views/movies/new.html.erb
<h1>create a new Movie</h1>
<%= form_with scope: :movie, url: movies_path, local: true do |f| %>
	<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %> 
	</p>

	<p>
    <%= f.label :genres %> <br>
    
     <%= f.select :geners, options_for_select([["Select genres", ""], "Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "History", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]) %>
	</p>

  <p>
    <%= f.label :year %> <br>
    <%= f.number_field :year %> 
	</p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %> 
	</p>

  <p>
    <%= f.label :director %> <br>
    <%= f.text_area :director %> 
	</p>

  <p>
    <%= f.label :main_star %> <br>
    <%= f.text_area :main_star %> 
	</p>


  <p>
    <%= f.submit %>
  </p>

<% end %>
<%= link_to 'Back',movies_path%>

app/views/movies/show.html.erb
<h1>Showing movies details</h1>

<p><strong>Title: </strong><%= @movies.name %></p>
<p><strong>Geners: </strong><%= @movies.geners %></p>
<p><strong>Year: </strong><%= @movies.year %></p>
<p><strong>director: </strong><%= @movies.director %></p>
<p><strong>Main_star: </strong><%= @movies.main_star %></p>
<%= link_to 'Back',movies_path%>

app/views/movies/userfav.html.erb
<h1>user's favorite movies page</h1>

<table border='2'>
  <thead>
    <tr>
      <th>favorites</th>
    </tr>
  </thead>
  <tbody>
  <% @favorites.each do |favorite|%>
  <tr>
    <td><%= favorite.movie.name %></td>
    <%# <td><%= favorite.user.username %></td> %>
  </tr>
  <% end %>
 </tbody>
</table>

<%= link_to 'Back',movies_userlist_path%>

app/views/movies/userlist.html.erb
<h1>Users listing page</h1>

<table border="2">
  <thead>
    <tr>
      <th>username</th>
      <th>favorited movies</th>
      <th>Delete User</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %> 
      <tr>
        <td><%= link_to user.username, "/movies/userlist/#{user.id}"%></td>
        <td><%=Favorite.where(user_id: user.id).count%></td>
        <td><%= link_to 'delete', user_path(user.id), method: :delete, data: {confirm: "Are You Sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back',movies_path%>

app/views/users/index.html.erb
 Logged in as <%= current_user.username %>

 <%= link_to 'my favorite movies list', users_list_path%>

<h1>Movies listing page</h1>
<table border="2">
  <thead>
    <tr>
      <th>name</th>
      <th>geners</th>
      <th>year</th>
      <th>director</th>
      <th>main_star</th>
      <th>show</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %> 
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.geners %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director %></td>
        <td><%= movie.main_star %></td>
        <td><%= link_to 'show', user_path(movie.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/list.html.erb
<h1>Your Favorite Movies list</h1>
<% @favorites.each do |favorite|%>
  <%= favorite.movie.name %><br>
<% end %>

 <%= link_to 'back to all movies list', users_path%>

app/views/users/new.html.erb
<h1> Create a new user </h1>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with scope: :user, url: users_path, local: true do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Showing movies details</h1>
<p><strong>Title: </strong><%= @movies.name %></p>
<p><strong>Geners: </strong><%= @movies.geners %></p>
<p><strong>Year: </strong><%= @movies.year %></p>
<p><strong>director: </strong><%= @movies.director %></p>
<p><strong>Main_star: </strong><%= @movies.main_star %></p>
<%= link_to favorite_text, favorites_update_path(movie: @movies), id: 'favorite_link', remote: true %>
<%= link_to 'Back',root_path%>

app/views/usersessions/create.html.erb
<h1>Usersessions#create</h1>
<p>Find me in app/views/usersessions/create.html.erb</p>

app/views/usersessions/destroy.html.erb
<h1>Usersessions#destroy</h1>
<p>Find me in app/views/usersessions/destroy.html.erb</p>

app/views/usersessions/new.html.erb
<p id=”alert”><%= alert %></p>
<h1>Login</h1>
<%= form_tag usersessions_path do |form| %>
  <div class=”field”>
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </div>
  <div class=”actions”>
    <%= submit_tag 'Login' %>
  </div>
<% end %>